name: Deploy Frontend

on:
  push:
    branches:
      - main

concurrency:
  group: pages
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  deploy:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Inject Firebase config
        run: |
        
          sed -i "s|%%API_KEY%%|${{ secrets.API_KEY }}|g" docs/Login/login.html
          sed -i "s|%%AUTH_DOMAIN%%|${{ secrets.AUTH_DOMAIN }}|g" docs/Login/login.html
          sed -i "s|%%API_KEY%%|${{ secrets.API_KEY }}|g" docs/auth-state.js
          sed -i "s|%%AUTH_DOMAIN%%|${{ secrets.AUTH_DOMAIN }}|g" docs/auth-state.js
          sed -i "s|%%API_KEY%%|${{ secrets.API_KEY }}|g" docs/Customer-Dashboard/customer-dashboard.html
          sed -i "s|%%AUTH_DOMAIN%%|${{ secrets.AUTH_DOMAIN }}|g" docs/Customer-Dashboard/customer-dashboard.html
          sed -i "s|%%API_KEY%%|${{ secrets.API_KEY }}|g" docs/Plumber-Dashboard/plumber-dashboard.html
          sed -i "s|%%AUTH_DOMAIN%%|${{ secrets.AUTH_DOMAIN }}|g" docs/Plumber-Dashboard/plumber-dashboard.html
          sed -i "s|%%API_KEY%%|${{ secrets.API_KEY }}|g" docs/Reset-Password/reset-password.html
          sed -i "s|%%AUTH_DOMAIN%%|${{ secrets.AUTH_DOMAIN }}|g" docs/Reset-Password/reset-password.html
          sed -i "s|%%API_KEY%%|${{ secrets.API_KEY }}|g" docs/Profile/profile.html
          sed -i "s|%%AUTH_DOMAIN%%|${{ secrets.AUTH_DOMAIN }}|g" docs/Profile/profile.html
          sed -i "s|%%GEMINI_KEY%%|${{ secrets.GEMINI_KEY }}|g" docs/button-behavior.js
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: gh-pages
          